export default {
  body: document.querySelector('body'),
  form: document.querySelector('.search form'),
  search: document.querySelector('.search form input'),
  loading: document.querySelector('.loading'),
  error: document.querySelector('.error'),
  city: document.querySelector('.city'),
  date: document.querySelector('.date'),
  temp_main: document.querySelector('.main'),
  temp_min: document.querySelector('.temp-min'),
  temp_max: document.querySelector('.temp-max'),
  feels_like: document.querySelector('.feels-like'),
  pressure: document.querySelector('.pressure'),
  humidity: document.querySelector('.humidity'),
  wind: document.querySelector('.wind'),
  visibility: document.querySelector('.visibility'),
  description: document.querySelector('.description'),
  icon: document.querySelector('.icon'),
  map: document.querySelector('.map'),
};
